# Generated by Django 6.0.2 on 2026-05-26 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('veterinarians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id_appointment', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('consultation_type', models.CharField(choices=[('general', 'Consulta General / Revision anual'), ('first', 'Primera Consulta'), ('sickness', 'Cita por Enfermedad'), ('emergency', 'Cita por Emergencia'), ('specialized', 'Consulta Especializada'), ('pre_surgical', 'Consulta Pre-quirurgica'), ('geriatric', 'Consulta Geriatrica'), ('telemedicine', 'Telemedicina'), ('nutrition', 'Consulta de Nutricion'), ('euthanasia', 'Eutanasia')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('in_progress', 'En Curso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No Asistio')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='veterinarians.veterinarian')),
            ],
        ),
    ]
