# Generated by Django 6.0.2 on 2026-05-26 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('bird', 'Ave'), ('rabbit', 'Conejo'), ('other', 'Otro')], max_length=20)),
                ('custom_species', models.CharField(blank=True, max_length=100, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('age_unit', models.CharField(choices=[('years', 'Años'), ('months', 'Meses')], default='years', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clients.client')),
            ],
        ),
    ]
